### ISSUE TITLE
question about project status

### ISSUE THREAD

**Issue by sivid** [sfodje/perlcritic#12]
Hello,
Some time ago I pushed a few commits to this project and was accepted, was wondering why did you `git push -f` everything, overwriting my commits?

Side question, is it ok if I upload my fork in VS marketplace?  I'll make sure to attribute to this project.

**Comment by sfodje** [comment]
Hello @sivid 
Sorry, I can't remember what happened to your commit, or what the commit was. It was most likely overwritten with a `git push -f` in a moment of impatience. I remember doing some re-writing a little while back.
I'm fine with you uploading your fork to the VS marketplace... I believe there's a least another fork of this up there already.
However, I could also add you as a collaborator to this project and give you permission to push to master. It's up to you 👍

**Comment by sivid** [comment]
Hey thanks :)
My main objective was to have some extension that people could install and write perl with vscode.  I just did some research, it seems anyone could package an extension and share privately with others, so I'll probably try that route first.  Good luck with the re-write!

p.s. if you want my commits, they're in Pull Requests section.
