### ISSUE TITLE
Update overview for how perlcritic.additionalArguments are used

### ISSUE THREAD

**Issue by ThomasNixon** [sfodje/perlcritic#3]
Please specify in the overview (or anywhere) that the array for perlcritic.additionalArguments is made up of element pairs.

Example (for those who need to know how to use it)
```
"perlcritic.additionalArguments": [
		"--profile", "C:/Users/User/Documents/.perlcritic_profile"
],
```

**Comment by sfodje** [comment]
Hello @ThomasNixon 
Thanks for bringing this to my attention. I'm in the middle of a time-sensitive project at the moment, but I'll make time to add that clarification over the weekend.
