### ISSUE TITLE
Process ANSI color code in perlcritic output

### ISSUE THREAD

**Issue by sivid** [sfodje/perlcritic#4]
OS: MacOS Sierra 10.12.6
Code version: Version 1.19.0-insider (1.19.0-insider) 2017-12-06
Perl was installed using perlbrew

I have disabled all other Perl plugins in VSCode.

This shows in the Output panel when `perlcritic.trace.server` is set to `verbose`:
```
[Trace - 6:09:38 PM] Received request 'window/showMessageRequest - (1)'.
Params: {
    "type": 1,
    "message": "Invalid output format (Please check your perltidy settings): \u001b[0m",
    "actions": []
}
```

For the record, there is a `~/.perltidyrc` file, with contents:
```
-pbp
-l=150
-ce
-pt=2
-bt=2
-sbt=2
-bbt=2
-isbc
```
although I'm pretty sure nobody's reading that

**Comment by sfodje** [comment]
Thanks @sivid. From next week, I'm off until the end of the year. I'll be happy to take care of this then.

**Comment by sivid** [comment]
The issue was caused by ANSI color code, not Unicode.  My bad.
